"""replace order with display_order

Revision ID: 6e0ff76ed392
Revises: d0ca2707d22b
Create Date: 2026-03-08 06:28:23.079207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e0ff76ed392'
down_revision: Union[str, Sequence[str], None] = 'd0ca2707d22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_id'), table_name='leaderboard')
    op.drop_table('leaderboard')
    op.alter_column('chapters', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('chapters_subject_id_fkey'), 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.alter_column('content_views', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('content_views', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_content_views_user', 'content_views', ['user_id'], unique=False)
    op.create_unique_constraint('unique_user_content_view', 'content_views', ['user_id', 'content_id'])
    op.drop_constraint(op.f('content_views_user_id_fkey'), 'content_views', type_='foreignkey')
    op.drop_constraint(op.f('content_views_content_id_fkey'), 'content_views', type_='foreignkey')
    op.create_foreign_key(None, 'content_views', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'content_views', 'questions', ['content_id'], ['id'], ondelete='CASCADE')
    op.add_column('exam_attempt_questions', sa.Column('question_id', sa.Integer(), nullable=True))
    op.alter_column('exam_attempt_questions', 'question_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('exam_attempt_questions', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exam_attempt_questions', 'options_json',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('exam_attempt_questions', 'correct_answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_exam_attempt_questions_id'), table_name='exam_attempt_questions')
    op.create_foreign_key(None, 'exam_attempt_questions', 'questions', ['question_id'], ['id'])
    op.add_column('exam_attempts', sa.Column('is_finished', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_exam_attempts_id'), table_name='exam_attempts')
    op.drop_column('exam_attempts', 'ip_address')
    op.drop_column('exam_attempts', 'leaderboard_processed')
    op.drop_column('exam_attempts', 'device_fingerprint')
    op.drop_column('exam_attempts', 'anti_cheat_flag')
    op.drop_column('exam_attempts', 'user_agent')
    op.add_column('exam_templates', sa.Column('ministry_year', sa.Integer(), nullable=True))
    op.add_column('exam_templates', sa.Column('ministry_round', sa.String(length=20), nullable=True))
    op.alter_column('exam_templates', 'difficulty',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_exam_templates_section_id'), 'exam_templates', ['section_id'], unique=False)
    op.create_index(op.f('ix_exam_templates_stage_id'), 'exam_templates', ['stage_id'], unique=False)
    op.create_index(op.f('ix_exam_templates_subject_id'), 'exam_templates', ['subject_id'], unique=False)
    op.drop_constraint(op.f('exam_templates_section_id_fkey'), 'exam_templates', type_='foreignkey')
    op.drop_constraint(op.f('exam_templates_stage_id_fkey'), 'exam_templates', type_='foreignkey')
    op.drop_constraint(op.f('exam_templates_subject_id_fkey'), 'exam_templates', type_='foreignkey')
    op.create_foreign_key(None, 'exam_templates', 'sections', ['section_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'exam_templates', 'subjects', ['subject_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'exam_templates', 'stages', ['stage_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_constraint(op.f('favorites_user_id_fkey'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('favorites_question_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.alter_column('monthly_resets', 'last_reset',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # op.create_unique_constraint('unique_monthly_reset', 'monthly_resets', ['id'])
    op.add_column('plans', sa.Column('description', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('plans_name_key'), 'plans', type_='unique')
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.alter_column('question_categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_question_categories_id'), table_name='question_categories')
    op.drop_constraint(op.f('question_categories_name_key'), 'question_categories', type_='unique')
    op.alter_column('question_category_link', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_category_link', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_question_statistics_question', 'question_statistics', ['question_id'], unique=False)
    op.create_unique_constraint('unique_question_statistics', 'question_statistics', ['question_id'])
    op.drop_constraint(op.f('question_statistics_question_id_fkey'), 'question_statistics', type_='foreignkey')
    op.create_foreign_key(None, 'question_statistics', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('question_types_name_key'), 'question_types', type_='unique')
    op.create_index(op.f('ix_question_types_name'), 'question_types', ['name'], unique=True)
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.String(length=10), nullable=True))
    op.add_column('questions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('ministry_round', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('total_attempts', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('correct_attempts', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('degree', sa.Integer(), nullable=True))
    op.alter_column('questions', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('questions_section_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.add_column('sections', sa.Column('order', sa.Integer(), nullable=True))
    op.alter_column('sections', 'chapter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('sections_chapter_id_fkey'), 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('stages', 'branch')
    op.alter_column('student_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_progress', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('unique_user_section_progress', 'student_progress', ['user_id', 'section_id'])
    op.drop_constraint(op.f('student_progress_user_id_fkey'), 'student_progress', type_='foreignkey')
    op.drop_constraint(op.f('student_progress_section_id_fkey'), 'student_progress', type_='foreignkey')
    op.create_foreign_key(None, 'student_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_progress', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subjects', 'stage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('subjects_stage_id_fkey'), 'subjects', type_='foreignkey')
    op.drop_constraint(op.f('subjects_branch_id_fkey'), 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'stages', ['stage_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subjects', 'branch_id')
    op.add_column('subscriptions', sa.Column('questions_used_today', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('payment_status', sa.String(length=20), nullable=True))
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_constraint(op.f('subscriptions_plan_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key(None, 'users', 'stages', ['stage_id'], ['id'])
    op.drop_column('users', 'free_ai_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_ai_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('subscriptions_plan_id_fkey'), 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('subscriptions', 'cancelled_at')
    op.drop_column('subscriptions', 'auto_renew')
    op.drop_column('subscriptions', 'payment_status')
    op.drop_column('subscriptions', 'questions_used_today')
    op.add_column('subjects', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(op.f('subjects_branch_id_fkey'), 'subjects', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(op.f('subjects_stage_id_fkey'), 'subjects', 'stages', ['stage_id'], ['id'])
    op.alter_column('subjects', 'stage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'student_progress', type_='foreignkey')
    op.drop_constraint(None, 'student_progress', type_='foreignkey')
    op.create_foreign_key(op.f('student_progress_section_id_fkey'), 'student_progress', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(op.f('student_progress_user_id_fkey'), 'student_progress', 'users', ['user_id'], ['id'])
    op.drop_constraint('unique_user_section_progress', 'student_progress', type_='unique')
    op.alter_column('student_progress', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('stages', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key(op.f('sections_chapter_id_fkey'), 'sections', 'chapters', ['chapter_id'], ['id'])
    op.alter_column('sections', 'chapter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('sections', 'order')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_section_id_fkey'), 'questions', 'sections', ['section_id'], ['id'])
    op.alter_column('questions', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('questions', 'degree')
    op.drop_column('questions', 'correct_attempts')
    op.drop_column('questions', 'total_attempts')
    op.drop_column('questions', 'ministry_round')
    op.drop_column('questions', 'is_active')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'explanation')
    op.drop_index(op.f('ix_question_types_name'), table_name='question_types')
    op.create_unique_constraint(op.f('question_types_name_key'), 'question_types', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'question_statistics', type_='foreignkey')
    op.create_foreign_key(op.f('question_statistics_question_id_fkey'), 'question_statistics', 'questions', ['question_id'], ['id'])
    op.drop_constraint('unique_question_statistics', 'question_statistics', type_='unique')
    op.drop_index('idx_question_statistics_question', table_name='question_statistics')
    op.alter_column('question_category_link', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_category_link', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(op.f('question_categories_name_key'), 'question_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_question_categories_id'), 'question_categories', ['id'], unique=False)
    op.alter_column('question_categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.create_unique_constraint(op.f('plans_name_key'), 'plans', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('plans', 'is_active')
    op.drop_column('plans', 'description')
    op.drop_constraint('unique_monthly_reset', 'monthly_resets', type_='unique')
    op.alter_column('monthly_resets', 'last_reset',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_question_id_fkey'), 'favorites', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(op.f('favorites_user_id_fkey'), 'favorites', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.alter_column('favorites', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'exam_templates', type_='foreignkey')
    op.drop_constraint(None, 'exam_templates', type_='foreignkey')
    op.drop_constraint(None, 'exam_templates', type_='foreignkey')
    op.create_foreign_key(op.f('exam_templates_subject_id_fkey'), 'exam_templates', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('exam_templates_stage_id_fkey'), 'exam_templates', 'stages', ['stage_id'], ['id'])
    op.create_foreign_key(op.f('exam_templates_section_id_fkey'), 'exam_templates', 'sections', ['section_id'], ['id'])
    op.drop_index(op.f('ix_exam_templates_subject_id'), table_name='exam_templates')
    op.drop_index(op.f('ix_exam_templates_stage_id'), table_name='exam_templates')
    op.drop_index(op.f('ix_exam_templates_section_id'), table_name='exam_templates')
    op.alter_column('exam_templates', 'difficulty',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('exam_templates', 'ministry_round')
    op.drop_column('exam_templates', 'ministry_year')
    op.add_column('exam_attempts', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exam_attempts', sa.Column('anti_cheat_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('exam_attempts', sa.Column('device_fingerprint', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exam_attempts', sa.Column('leaderboard_processed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('exam_attempts', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_exam_attempts_id'), 'exam_attempts', ['id'], unique=False)
    op.drop_column('exam_attempts', 'is_finished')
    op.drop_constraint(None, 'exam_attempt_questions', type_='foreignkey')
    op.create_index(op.f('ix_exam_attempt_questions_id'), 'exam_attempt_questions', ['id'], unique=False)
    op.alter_column('exam_attempt_questions', 'correct_answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exam_attempt_questions', 'options_json',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('exam_attempt_questions', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exam_attempt_questions', 'question_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('exam_attempt_questions', 'question_id')
    op.drop_constraint(None, 'content_views', type_='foreignkey')
    op.drop_constraint(None, 'content_views', type_='foreignkey')
    op.create_foreign_key(op.f('content_views_content_id_fkey'), 'content_views', 'questions', ['content_id'], ['id'])
    op.create_foreign_key(op.f('content_views_user_id_fkey'), 'content_views', 'users', ['user_id'], ['id'])
    op.drop_constraint('unique_user_content_view', 'content_views', type_='unique')
    op.drop_index('idx_content_views_user', table_name='content_views')
    op.alter_column('content_views', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content_views', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key(op.f('chapters_subject_id_fkey'), 'chapters', 'subjects', ['subject_id'], ['id'])
    op.alter_column('chapters', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('leaderboard',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('highest_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_exams', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('competitive_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name=op.f('leaderboard_stage_id_fkey')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('leaderboard_subject_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('leaderboard_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leaderboard_pkey'))
    )
    op.create_index(op.f('ix_leaderboard_id'), 'leaderboard', ['id'], unique=False)
    # ### end Alembic commands ###
