"""sync models

Revision ID: ff0b80ca6c0f
Revises: 6e0ff76ed392
Create Date: 2026-03-08 07:11:37.994457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0b80ca6c0f'
down_revision: Union[str, Sequence[str], None] = '6e0ff76ed392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_templates', sa.Column('display_order', sa.Integer(), nullable=True))
    op.drop_column('exam_templates', 'order')
   # op.create_unique_constraint('unique_monthly_reset', 'monthly_resets', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_monthly_reset', 'monthly_resets', type_='unique')
    op.add_column('exam_templates', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('exam_templates', 'display_order')
    # ### end Alembic commands ###
